# Generated by Django 4.2.8 on 2023-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_at',
            field=models.DateField(),
        ),
    ]
